### ISSUE TITLE
Error: Failed merge with upstream for cloud-init

### ISSUE THREAD

**Issue by manojdelphix** [delphix/linux-pkg#78]
The linux-pkg-update job failed to merge with upstream for cloud-init.

job: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-update/job/master/job/userland/job/update/319/consoleFull

> 19:21:25  PACKAGE cloud-init: STAGE update_upstream COMPLETED in 1 seconds
> 19:21:25  
> 19:21:25  Running: rm /var/tmp/jenkins/workspace/devops-gate/master/linux-pkg-update/master/userland/update/linux-pkg/packages/cloud-init/tmp/updating-upstream
> 19:21:25  Running: touch /var/tmp/jenkins/workspace/devops-gate/master/linux-pkg-update/master/userland/update/linux-pkg/packages/cloud-init/tmp/merging
> 19:21:25  Running: merge_with_upstream
> 19:21:25  Running: cd /var/tmp/jenkins/workspace/devops-gate/master/linux-pkg-update/master/userland/update/linux-pkg/packages/cloud-init/tmp/repo
> 19:21:25  Running: git checkout -q repo-HEAD
> 19:21:25  Running: git merge --no-edit refs/heads/upstream-HEAD
> 19:21:25  Removing tests/unittests/test_handler/test_handler_snappy.py
> 19:21:25  Removing tests/cloud_tests/testcases/modules/snappy.yaml
> 19:21:25  Removing tests/cloud_tests/testcases/modules/snappy.py
> 19:21:25  Auto-merging cloudinit/ssh_util.py
> 19:21:25  CONFLICT (content): Merge conflict in cloudinit/ssh_util.py
> 19:21:25  Removing cloudinit/config/cc_snappy.py
> 19:21:25  Removing cloudinit/config/cc_snap_config.py
> 19:21:25  Automatic merge failed; fix conflicts and then commit the result.
> 19:21:25  git merge failed
> 19:21:25  Running: git merge --abort
> 19:21:25  Error: failed command 'merge_with_upstream'
> 19:21:25  Error: Failed merge with upstream for cloud-init
> 19:21:25  Error: buildpkg.sh failed.

**Comment by pzakha** [comment]
Closing this as this is a merge conflict in the cloud-init repository and not a linux-pkg issue.
```
 19:21:25 CONFLICT (content): Merge conflict in cloudinit/ssh_util.py
```
Often merge conflicts are resolved without bugs, however this one does have a bug opened already as it is a bit more involved: DLPX-68333.
