### ISSUE TITLE
intermittent job failures due to wget failing to fetch swarm-client-3.14.jar from artifactory

### ISSUE THREAD

**Issue by sdimitro** [delphix/linux-pkg#8]
```
03:29:32 jenkins-swarm-connect.sh: failed to wget http://XXXXXX/jenkins-ci/plugins/swarm-client/3.14/swarm-client-3.14.jar
```

Links:

- http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/post-push/86/execution/node/44/log/
- http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/master/job/update/38/execution/node/44/log/

**Comment by jgallag88** [comment]
Likely related to https://delphix.slack.com/archives/C02SKTFTJ/p1545765367011600 and https://jira.delphix.com/browse/TOOL-7006
